language: node_js

node_js:
  - node #latest stable Node.js release
  - iojs #latest stable io.js release
  - 6 #latest 6.x release
  - 5 #latest 5.x release
  - 4 #latest 5.x release

install:
    - npm install

script:
    - npm test
